name: Perl CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'

    - name: Update CPAN and cpanminus
      run: |
        cpan App::cpanminus
        cpanm --self-upgrade

    - name: Install Dependencies
      run: |
        cpanm --installdeps --notest .

    - name: Run Tests
      run: |
        prove -l
